apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bot-wsp-whapi-ia-1-0
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/timeout: "300"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: northamerica-south1-docker.pkg.dev/gen-lang-client-0318357688/cloud-run-source-deploy/bot-wsp-whapi-ia-1.0/bot-wsp-whapi-ia-1-0:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "production"
        # Agrega aquí tus variables de entorno secretas
        # - name: OPENAI_API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: bot-secrets
        #       key: openai-api-key
        # - name: WHAPI_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: bot-secrets
        #       key: whapi-token
        # - name: ASSISTANT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: bot-secrets
        #       key: assistant-id
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true 