steps:
  # Build step
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bot-wsp-whapi-ia', '.']

  # Deploy step
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bot-wsp-whapi-ia'
      - '--image=gcr.io/$PROJECT_ID/bot-wsp-whapi-ia'
      - '--region=northamerica-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=540'
      - '--concurrency=1'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--no-cpu-throttling'
      - '--set-env-vars=NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/bot-wsp-whapi-ia'

# Configuración adicional
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Configuración de timeout
timeout: '1200s' 