[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"